### ISSUE TITLE
Integration test failures

### ISSUE THREAD

**Issue by arlimus** [chef/train#34]
Currently test kitchen integration tests fail:

```
         1) Error:
       run_command#test_0002_is not running sudo without password:
       Train::UserError: Sudo failed: Sudo requires a password, please configure it.
           /tmp/kitchen/data/lib/train/extras/command_wrapper.rb:101:in `load'
           /tmp/kitchen/data/lib/train/transports/local.rb:27:in `initialize'
           /tmp/kitchen/data/lib/train/transports/local.rb:19:in `new'
           /tmp/kitchen/data/lib/train/transports/local.rb:19:in `connection'
           /tmp/kitchen/data/test/integration/sudo/run_as.rb:11:in `run_as'
           test/integration/sudo/passwd.rb:13:in `block (2 levels) in <main>'
       

>>>>> Converge failed on instance <default-centos-511>.
>>>>>> Please see .kitchen/logs/default-centos-511.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by srenatus** [comment]
Interesting, the password of the users `passwd` and `nopasswd` doesn't work. Doesn't work with `ssh passwd@127.0.0.1` or passwd(1) for changing passwords either.
